server:
  port: 9914
spring:
  config:
    import: nacos:common-test-value.yml
  application:
    name: common-test
  profiles:
    active: value,formal,private
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 172.23.104.184
      config:
        server-addr: 172.23.104.184
        file-extension: yml
        username: nacos
        password: nacos